import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { getPostSlugs, Post } from "@api";

interface HomeProps {
  posts: string[];
  title: string;
}

const Home: React.FC<HomeProps> = (props: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devroll</title>
        <meta name="description" content="Generated by create next app" />
        {props.posts.map((p) => {
          return <div key={p}>{p}</div>;
        })}
      </Head>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const allPosts = await getPostSlugs();

  return {
    props: {
      posts: allPosts,
      title: "Devroll",
    },
  };
}
