import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { getConfig, getAllPosts } from "@api";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devroll</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    </div>
  );
}

export async function getStaticProps() {
  const config = await getConfig();
  const allPosts = await getAllPosts();

  return {
    props: {
      posts: allPosts,
      title: config.title,
      description: config.description,
    },
  };
}
